/* tslint:disable */
/* eslint-disable */
/**
 * Terinla
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailNotification
 */
export interface EmailNotification {
    /**
     * 
     * @type {string}
     * @memberof EmailNotification
     */
    to?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailNotification
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailNotification
     */
    body?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EmailNotification
     */
    sent?: boolean;
}

/**
 * Check if a given object implements the EmailNotification interface.
 */
export function instanceOfEmailNotification(value: object): value is EmailNotification {
    return true;
}

export function EmailNotificationFromJSON(json: any): EmailNotification {
    return EmailNotificationFromJSONTyped(json, false);
}

export function EmailNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'] == null ? undefined : json['to'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'body': json['body'] == null ? undefined : json['body'],
        'sent': json['sent'] == null ? undefined : json['sent'],
    };
}

export function EmailNotificationToJSON(json: any): EmailNotification {
    return EmailNotificationToJSONTyped(json, false);
}

export function EmailNotificationToJSONTyped(value?: EmailNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'subject': value['subject'],
        'body': value['body'],
        'sent': value['sent'],
    };
}

